name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:      
  deploy:
    runs-on: ubuntu-latest
    # This step is for typical static websites
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@master
    #   - name: Upload to S3
    #     uses: jakejarvis/s3-sync-action@master
    #     env:
    #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       AWS_REGION: 'us-west-2'
    #       SOURCE_DIR: 'website'
    

    # This step is for React apps
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: cd resume_app && npm install && npm run build && cd ..
      # - name: Test website
      #   run: npm run test
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'src/build'
      


      - name: Invalidate CloudFront cache
        uses: awact/cloudfront-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_REGION: 'us-west-2'
          PATHS: '/*'